#ifndef CONFIG_H_
#define CONFIG_H_

#include <utility>
#include <vector>
#include <climits>

// Global
const int CLIENT_SCREEN_WIDTH = 648;
const int CLIENT_SCREEN_HEIGHT = 768;

const int ARRAY_SHUFFLE_AMOUNT = 20;

// Scheduler
const double SCHEDULER_FRAME_RATE_DT = 1.0 / 60.0; //60.0

// Graphics
const int GRAPHICS_NUM_BITMAPS = 105;

const int GRAPHICS_BITMAPS_UNIT_OFFSET = 7;

//unit circle (haha)
//definitely hard coded, but I didn't want to draw a circle with trig...
//I do that with tower radius though.
const int GRAPHICS_BITMAP_UNIT_CIRCLE_ROWS[] {
    5, 9, 11, 13, 13, 15, 15, 15, 15, 15, 13, 13, 11, 9, 5
};
const int GRAPHICS_BITMAP_UNIT_CIRCLE_OFFSET[] {
    5, 3, 2, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 3, 5
};

const double GRAPHICS_TOWER_RADIUS = 3.5;
const int GRAPHICS_TOWER_RADIUS_BORDER_WIDTH = 2;
const double GRAPHICS_TOWER_RADIUS_ALPHA = 0.5;
const int GRAPHICS_TOWER_RADIUS_BORDER_FILLABLE_COLOR = 0xFF000050;
const int GRAPHICS_TOWER_RADIUS_BORDER_UNFILLABLE_COLOR = 0xFF500000;
const unsigned int GRAPHICS_TOWER_LASER_COLORS[4] {
    0xFF0000FF, 0xFFFF0000, 0xFF00D662, 0xFFFFFF00
};


const int GRAPHICS_MAX_WORLD_UPDATES = 64;

// Graphics_UI
const int GRAPHICS_UI_NUM_BOLTS = 4;
const std::pair<int, int> GRAPHICS_UI_BOLTS_XYS[GRAPHICS_UI_NUM_BOLTS] = {
    {92, 92},
    {484, 92},
    {92, 604},
    {484, 604}
};

// clockwise order starting at the top
const int GRAPHICS_UI_LOADING_DELAY = 5;
const int GRAPHICS_UI_NUM_LOADINGS = 8;
const std::pair<int, int> GRAPHICS_UI_LOADING_XYS[GRAPHICS_UI_NUM_LOADINGS] = {
    {308, 288},
    {365, 311},
    {388, 368},
    {365, 425},
    {308, 448},
    {251, 425},
    {228, 368},
    {251, 311}
};

const int MECHANICS_WORLD_STATE_WIDTH = 25;
const int MECHANICS_WORLD_STATE_HEIGHT = 25;

const int GRAPHICS_UI_MAIN_ARENA_INSET_X = 24;
const int GRAPHICS_UI_MAIN_ARENA_INSET_Y = 24;
const int GRAPHICS_UI_MAIN_ARENA_CELL_SIZE = 24;
const int GRAPHICS_UI_MAIN_ARENA_WIDTH = MECHANICS_WORLD_STATE_WIDTH * GRAPHICS_UI_MAIN_ARENA_CELL_SIZE;
const int GRAPHICS_UI_MAIN_ARENA_HEIGHT = MECHANICS_WORLD_STATE_HEIGHT * GRAPHICS_UI_MAIN_ARENA_CELL_SIZE;
const int GRAPHICS_UI_MAIN_ARENA_HALF_CELL_SIZE = 12;
const int GRAPHICS_UI_MAIN_NUM_BUTTONS = 5;
const int GRAPHICS_UI_MAIN_BUTTONS_SIZE = 72;
const int GRAPHICS_UI_MAIN_BUTTONS_SPREAD = 48;
const std::pair<int, int> GRAPHICS_UI_MAIN_BUTTONS_XYS[GRAPHICS_UI_MAIN_NUM_BUTTONS] = {
    {48, 672},
    {168, 672},
    {288, 672},
    {408, 672},
    {528, 672}
};

// position, size
const std::pair<int, int> GRAPHICS_UI_MAIN_BUTTONS_CONTINUE[2] = {
    {234, 654},
    {180, 72}
};

const int GRAPHICS_UI_NUM_MONEY = 40;
const std::pair<int, int> GRAPHICS_UI_MONEY_XYS[GRAPHICS_UI_NUM_MONEY] = {
    {33, 632},
    {63, 632},
    {93, 632},
    {123, 632},
    {153, 632},
    {183, 632},
    {213, 632},
    {243, 632},
    {273, 632},
    {303, 632},
    {333, 632},
    {363, 632},
    {393, 632},
    {423, 632},
    {453, 632},
    {483, 632},
    {513, 632},
    {543, 632},
    {573, 632},
    {603, 632},
    {33, 652},
    {63, 652},
    {93, 652},
    {123, 652},
    {153, 652},
    {183, 652},
    {213, 652},
    {243, 652},
    {273, 652},
    {303, 652},
    {333, 652},
    {363, 652},
    {393, 652},
    {423, 652},
    {453, 652},
    {483, 652},
    {513, 652},
    {543, 652},
    {573, 652},
    {603, 652}
};

// Bitmap IDS
enum class BitmapID {
    BLUE_CIRCLE_BUTTON,
    BLUE_CIRCLE_PRESSED,
    BLUE_CIRCLE_UNIT,
    BLUE_GOAL,
    BLUE_GOAL_SELECTED,
    BLUE_SQUARE_BUTTON,
    BLUE_SQUARE_PRESSED,
    BLUE_SQUARE_UNIT,
    BLUE_TOWER_BUTTON,
    BLUE_TOWER_PRESSED,
    BLUE_TRIANGLE_BUTTON,
    BLUE_TRIANGLE_PRESSED,
    BLUE_TRIANGLE_UNIT,
    BOLT,
    DEAD_GOAL,
    EDGE_BOTTOM_LEFT,
    EDGE_BOTTOM_RIGHT,
    EDGE_GOAL_BOTTOM,
    EDGE_GOAL_LEFT,
    EDGE_GOAL_RIGHT,
    EDGE_GOAL_TOP,
    EDGE_HORIZONTAL,
    EDGE_TOP_LEFT,
    EDGE_TOP_RIGHT,
    EDGE_VERTICAL,
    EMPTY_TILE_BOTH,
    EMPTY_TILE_BOTTOM,
    EMPTY_TILE_NEITHER,
    EMPTY_TILE_RIGHT,
    GREEN_CIRCLE_BUTTON,
    GREEN_CIRCLE_PRESSED,
    GREEN_CIRCLE_UNIT,
    GREEN_GOAL,
    GREEN_GOAL_SELECTED,
    GREEN_SQUARE_BUTTON,
    GREEN_SQUARE_PRESSED,
    GREEN_SQUARE_UNIT,
    GREEN_TOWER_BUTTON,
    GREEN_TOWER_PRESSED,
    GREEN_TRIANGLE_BUTTON,
    GREEN_TRIANGLE_PRESSED,
    GREEN_TRIANGLE_UNIT,
    LOADING_EMPTY,
    LOADING_FILLED,
    MAIN_BACKGROUND,
    MAIN_X_BUTTON,
    MAIN_X_PRESSED,
    MONEY_EMPTY,
    MONEY_FILLED,
    RED_CIRCLE_BUTTON,
    RED_CIRCLE_PRESSED,
    RED_CIRCLE_UNIT,
    RED_GOAL,
    RED_GOAL_SELECTED,
    RED_SQUARE_BUTTON,
    RED_SQUARE_PRESSED,
    RED_SQUARE_UNIT,
    RED_TOWER_BUTTON,
    RED_TOWER_PRESSED,
    RED_TRIANGLE_BUTTON,
    RED_TRIANGLE_PRESSED,
    RED_TRIANGLE_UNIT,
    TOWER_BLUE,
    TOWER_GREEN,
    TOWER_RADIUS,
    TOWER_RED,
    TOWER_YELLOW,
    UI_BACK_BUTTON,
    UI_BACKGROUND,
    UI_BACK_PRESSED,
    UI_BUTTON_PRESSED_TEMPLATE,
    UI_BUTTON_TEMPLATE,
    UI_CONTINUE_BUTTON,
    UI_CONTINUE_PRESSED,
    UI_HUMAN_BUTTON,
    UI_HUMAN_EMPTY,
    UI_HUMAN_FULL,
    UI_HUMAN_PRESSED,
    UI_ROBOT,
    UI_ROBOT_PRESSED,
    UI_X_BUTTON,
    UI_X_PRESSED,
    UNAVAILABLE_CIRCLE,
    UNAVAILABLE_SQUARE_BUTTON,
    UNAVAILABLE_TOWER,
    UNAVAILABLE_TRIANGLE_BUTTON,
    WALL_BUTTON,
    WALL_PRESSED,
    WALL_UNAVAILABLE,
    WOOD_WALL,
    WOOD_WALL_CURSOR_UNAVAILABLE,
    WOOD_WALL_UNPLACE,
    YELLOW_CIRCLE_BUTTON,
    YELLOW_CIRCLE_PRESSED,
    YELLOW_CIRCLE_UNIT,
    YELLOW_GOAL,
    YELLOW_GOAL_SELECTED,
    YELLOW_SQUARE_BUTTON,
    YELLOW_SQUARE_PRESSED,
    YELLOW_SQUARE_UNIT,
    YELLOW_TOWER_BUTTON,
    YELLOW_TOWER_PRESSED,
    YELLOW_TRIANGLE_BUTTON,
    YELLOW_TRIANGLE_PRESSED,
    YELLOW_TRIANGLE_UNIT,
};

//Mechanics
const int MECHANICS_MAX_NUM_PLAYERS = 4;
const int MECHANICS_MAX_TOWERS_PER_PLAYER = 5;
const int MECHANICS_PLAYER_STARTING_MONEY = 5000;
const int MECHANICS_GOAL_STARTING_HEALTH = 20;
const int MECHANICS_UNIT_STARTING_HEALTH = 2;
const int MECHANICS_WALL_STARTING_HEALTH = 5;
const int MECHANICS_TOWER_STARTING_HEALTH = 10;
const int MECHANICS_UNIT_PARTIAL_DAMAGE = 1;
const int MECHANICS_TOWER_RADIUS = 3;
const int MECHANICS_TWICE_TOWER_RADIUS = 6;
const int MECHANICS_TOWER_WORLD_RADIUS = (GRAPHICS_UI_MAIN_ARENA_CELL_SIZE * MECHANICS_TOWER_RADIUS) + GRAPHICS_UI_MAIN_ARENA_HALF_CELL_SIZE;

const int MECHANICS_MONEY_AMPLIFIER = 1000;
const int MECHANICS_UNIT_PRICE = 1000;
const int MECHANICS_TOWER_PRICE = 20000;
const int MECHANICS_WALL_PRICE = 1000;
const int MECHANICS_MONEY_PER_FRAME = 17;

const int MECHANICS_UNIT_SPACE_AMPLIFIER = 10000;
const int MECHANICS_UNIT_MOVE_ADJACENT = 5000;
const int MECHANICS_UNIT_MOVE_DIAGONAL = 3536;
const int MECHANICS_UNIT_SPACE_AMP_BY_ARENA = MECHANICS_UNIT_SPACE_AMPLIFIER * GRAPHICS_UI_MAIN_ARENA_CELL_SIZE;

const int MECHANICS_UNIT_COLLISION_DISTANCE = GRAPHICS_BITMAPS_UNIT_OFFSET * 2 + 1;
const int MECHANICS_UNIT_COLLISION_DISTANCE_UNIT_SPACE = MECHANICS_UNIT_COLLISION_DISTANCE * MECHANICS_UNIT_SPACE_AMPLIFIER;
const int MECHANICS_UNIT_COLLISION_DISTANCE_SQUARED = MECHANICS_UNIT_COLLISION_DISTANCE * MECHANICS_UNIT_COLLISION_DISTANCE;

const int MECHANICS_UNIT_WORLD_BOTTOM_EXTREME = (GRAPHICS_UI_MAIN_ARENA_CELL_SIZE * (MECHANICS_WORLD_STATE_HEIGHT + 1)) * MECHANICS_UNIT_SPACE_AMPLIFIER;
const int MECHANICS_UNIT_WORLD_RIGHT_EXTREME = (GRAPHICS_UI_MAIN_ARENA_CELL_SIZE * (MECHANICS_WORLD_STATE_WIDTH + 1)) * MECHANICS_UNIT_SPACE_AMPLIFIER;

enum class PlayerColor {
    BLUE = 1,
    RED,
    GREEN,
    YELLOW
};

enum class UnitType {
    SQUARE,
    TRIANGLE,
    CIRCLE
};

const int MECHANICS_GAME_STATE_MAX_UNITS = 512;
const int MECHANICS_GAME_STATE_MAX_UNITS_PER_BUCKET = 128;

enum class TowerTargetType {
    TOWER,
    WALL
};

const int MECHANICS_TOWER_START_DELAY = 5;
const int MECHANICS_TOWER_FIRING_DELAY = 50;
const int MECHANICS_TOWER_FIRING_LENGTH = 3;

//World State

enum class WorldStateID {
    EMPTY_BOTH,
    EMPTY_RIGHT,
    EMPTY_BOTTOM,
    EMPTY_NEITHER,
    EDGE_HORIZONTAL,
    EDGE_VERTICAL,
    EDGE_CORNER_TOP_LEFT,
    EDGE_CORNER_TOP_RIGHT,
    EDGE_CORNER_BOTTOM_LEFT,
    EDGE_CORNER_BOTTOM_RIGHT,
    EDGE_GOAL_LEFT,
    EDGE_GOAL_RIGHT,
    EDGE_GOAL_TOP,
    EDGE_GOAL_BOTTOM,
    DEAD_GOAL,
    GOAL_BLUE,
    GOAL_RED,
    GOAL_GREEN,
    GOAL_YELLOW,
    BLUE_TOWER,
    RED_TOWER,
    GREEN_TOWER,
    YELLOW_TOWER,
    WALL
};

const int MECHANICS_NUM_GOALS = 3;
const std::vector<std::pair<int, int>> MECHANICS_WORLD_STATE_GOALS_XYS[MECHANICS_MAX_NUM_PLAYERS] = {
    {{6, 0}, {12, 0}, {18, 0}}, //top
    {{24, 6}, {24, 12}, {24, 18}}, //right
    {{6, 24}, {12, 24}, {18, 24}}, //bottom
    {{0, 6}, {0, 12}, {0, 18}} //left
};

// User State
enum class UserSelect {
    NONE,
    CIRCLE,
    SQUARE,
    TRIANGLE,
    TOWER_MODE,
    PLACE_TOWER,
    DELETE_TOWER,
    TOWER,
    WALL_MODE,
    PLACE_WALL,
    TOWER_TARGETS,
    CONTINUE
};

enum class UserStateButtonID {
    TOWER_BUTTON,
    SQUARE_BUTTON,
    TRIANGLE_BUTTON,
    CIRCLE_BUTTON,
    TOWER_PRESSED,
    SQUARE_PRESSED,
    TRIANGLE_PRESSED,
    CIRCLE_PRESSED
};

// UI Module
enum class UIState {
    NONE,
    QUIT,
    MAIN_MENU,
    SINGLE_PLAYER,
    MULTI_PLAYER,
    LOADING
};

const int UI_DEFAULT_DELAY = 5;

const int UI_NUM_SCREENS_WITH_BUTTONS = 2;
const std::vector<std::pair<int, int>> UI_BUTTONS_XYS[UI_NUM_SCREENS_WITH_BUTTONS] {
    {{234, 252}, {234, 348}, {288, 444}}, // main menu
    {{234, 168}, {234, 264}, {234, 360}, {234, 456}} // single/multi
};

const std::vector<std::pair<int, int>> UI_BUTTONS_FLAVORS[] {
    {{63, 19}, {99, 19}}, //2
    {{45, 19}, {81, 19}, {117, 19}}, //3
    {{26, 19}, {62, 19}, {98, 19}, {134, 19}}, //4
    
};

// Listener
// MainInput
enum class MainInputID {
    DO_NOTHING,
    CREATE_SQUARE,
    CREATE_TRIANGLE,
    CREATE_CIRCLE,
    BUILD_WALL,
    BUILD_TOWER,
    REMOVE_TOWER,
    TOWER_TARGETS,
    CONTINUE
};

enum class MainClickID {
    NONE,
    WALL_BUTTON,
    TOWER_BUTTON,
    CIRCLE_BUTTON,
    TRIANGLE_BUTTON,
    SQUARE_BUTTON,
    GRID,
    CONTINUE
};

//Networking
const int NETWORKING_FRAME_DELAY = 5;
const int NETWORKING_MAX_PACKETS = (NETWORKING_FRAME_DELAY + 1) * MECHANICS_MAX_NUM_PLAYERS;
const int NETWORKING_MULTIPLAYER_BUFFER_SIZE = 2048;

//AI
enum class AIUpdateType {
    ADD_WALL,
    ADD_TOWER,
    REMOVE_WALL,
    REMOVE_TOWER,
    REMOVE_GOAL
};

const int MECHANICS_AI_FILLABLE_ARENA_WITH_OFFSET = GRAPHICS_UI_MAIN_ARENA_CELL_SIZE + GRAPHICS_BITMAPS_UNIT_OFFSET;

const int MECHANICS_AI_VALUE_ITERATION_CP_VALUE = 1000000;
const int MECHANICS_AI_VALUE_ITERATION_TOWER_COST = 10000;
const int MECHANICS_AI_VALUE_ITERATION_ADJACENT_COST = 10000;
const int MECHANICS_AI_VALUE_ITERATION_DIAGONAL_COST = 14142;
const int MECHANICS_AI_VALUE_ITERATION_MIN_VALUE = INT_MIN + (32 * MECHANICS_AI_VALUE_ITERATION_TOWER_COST);

enum class UnitDirection {
    UP,
    RIGHT,
    DOWN,
    LEFT,
    UP_RIGHT,
    DOWN_RIGHT,
    DOWN_LEFT,
    UP_LEFT
};

#endif